//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robit.WordFilter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BLACKLIST {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLACKLIST() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robit.WordFilter.BLACKLIST", typeof(BLACKLIST).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Arse&quot;,&quot;Ass&quot;,&quot;Asshole&quot;,&quot;Homosexual&quot;,&quot;Homophobic&quot;,&quot;Racist&quot;,&quot;Gay&quot;,&quot;Lgbt&quot;,&quot;Jew&quot;,&quot;Jewish&quot;,&quot;Anti-semitic&quot;,&quot;Chink&quot;,&quot;Muslims&quot;,&quot;Muslim&quot;,&quot;Isis&quot;,&quot;Islamophobe&quot;,&quot;homophobe &quot;,&quot;Bombing&quot;,&quot;Sexyhot&quot;,&quot;Bastard&quot;,&quot;Bitch&quot;,&quot;Fucker&quot;,&quot;Cunt&quot;,&quot;Damn&quot;,&quot;Fuck&quot;,&quot;Goddamn&quot;,&quot;Shit&quot;,&quot;Motherfucker&quot;,&quot;Nigga&quot;,&quot;Nigger&quot;,&quot;Prick&quot;,&quot;Shit&quot;,&quot;shit ass&quot;,&quot;Shitass&quot;,&quot;son of a bitch&quot;,&quot;Whore&quot;,&quot;Thot&quot;,&quot;Slut&quot;,&quot;Faggot&quot;,&quot;Dick&quot;,&quot;Pussy&quot;,&quot;Penis&quot;,&quot;Vagina&quot;,&quot;Negro&quot;,&quot;Coon&quot;,&quot;Bitched&quot;,&quot;Sexist&quot;,&quot;Freaking&quot;,&quot;Cock&quot;,&quot;Sucker&quot;,&quot;Lick&quot;,&quot;Licker&quot;,&quot;Rape&quot;,&quot;Moles....
        /// </summary>
        internal static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
    }
}
